name: sam.clrk.space
title: sam clarke's online space

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-mentions

#baseurl: "/"

defaults:
  -
    scope:
      path:            "_posts/*.md"
    values:
      sitemap:         true

repository: smclrk/samclarke.blog
permalink: pretty

jekyll-mentions:
  base_url: https://twitter.com